apiVersion: v1
kind: Service
metadata:
  name: my-country-service
spec:
  type: NodePort
  selector:
    app: country-service
  ports:
    - port: 8087
      targetPort: 8087
      nodePort: 30007
      protocol: TCP

